// Core session management

export { type Args, parseArgs } from "./cli/args.ts";
// Config paths
export { getAgentDir, VERSION } from "./config.ts";
export {
	AgentSession,
	type AgentSessionConfig,
	type AgentSessionEvent,
	type AgentSessionEventListener,
	type ModelCycleResult,
	type ParsedSkillBlock,
	type PromptOptions,
	parseSkillBlock,
	type SessionStats,
} from "./core/agent-session.ts";
// Auth and model registry
export {
	type ApiKeyCredential,
	type AuthCredential,
	type AuthStatus,
	AuthStorage,
	type AuthStorageBackend,
	FileAuthStorageBackend,
	InMemoryAuthStorageBackend,
	type OAuthCredential,
} from "./core/auth-storage.ts";
export {
	type ApiAction,
	ApiBroker,
	type ApiMethod,
	type ApiOutcome,
	AUTOPILOT_MAX,
	type AutomationHarnessScoreInput,
	AutomationHarnessScorer,
	type AutomationScoreBreakdown,
	type AutomationTrace,
	type AutomationTraceAction,
	type AutomationTraceContextPlan,
	type AutomationTraceEnvApiUse,
	type AutonomyProfile,
	type BrokerFetcher,
	type BrokerFetchRequest,
	type BrokerFetchResponse,
	type Capability,
	canonicalHash,
	classifyEnvKey,
	DynamicToolPortfolioOptimizer,
	EnvBroker,
	type EnvBrokerLedger,
	type EnvMode,
	type EnvRecord,
	type EnvResolutionRequest,
	type EnvUseEvent,
	type EvidenceActor,
	type EvidenceEvent,
	type EvidenceEventInput,
	EvidenceLedger,
	type EvidenceOutcome,
	type EvidencePointer,
	type ExecutionStrategy,
	type Postcondition,
	PostconditionVerifier,
	type RiskLevel,
	redactForModel,
	type Sensitivity,
	strategyForRisk,
	ToolExecutionBroker,
	type ToolExecutionCandidate,
	type ToolExecutionChoice,
	type ToolExecutionNeed,
	type VerificationContext,
	type VerificationResult,
} from "./core/automation/index.ts";
// Compaction
export {
	type BranchPreparation,
	type BranchSummaryResult,
	type CollectEntriesResult,
	type CompactionBarrierResult,
	type CompactionCommitDecision,
	type CompactionEnvelope,
	type CompactionHysteresisConfig,
	type CompactionHysteresisState,
	type CompactionResult,
	type CompactionTransaction,
	type CutPointResult,
	calculateContextTokens,
	collectEntriesForBranchSummary,
	compact,
	createCompactionEnvelope,
	createCompactionHysteresisConfig,
	createCompactionHysteresisState,
	createCompactionSourceIdentity,
	createCompactionTransaction,
	createSessionRevisionToken,
	DEFAULT_COMPACTION_SETTINGS,
	decideCompactionCommit,
	estimateTokens,
	evaluateCompactionBarrier,
	type FileOperations,
	findCutPoint,
	findTurnStartIndex,
	type GenerateBranchSummaryOptions,
	generateBranchSummary,
	generateSummary,
	getLastAssistantUsage,
	prepareBranchEntries,
	serializeConversation,
	shouldCompact,
	stepCompactionHysteresis,
	validateCompactionEnvelope,
} from "./core/compaction/index.ts";
export {
	applyContextCacheInvalidation,
	buildContextBudgetMaterializedRepresentationCacheKeyV2,
	buildContextBudgetPlanCacheKeyV2,
	CONTEXT_BUDGET_POLICY_VERSION_V2,
	type ContextBudgetCacheProviderV2,
	type ContextCacheInvalidationEvent,
	type ContextCacheInvalidationSnapshot,
	createContextBudgetCacheKeyBaseV2,
	createContextCacheInvalidationSnapshot,
	createMemoryContextBudgetCacheProviderV2,
	planPromptContextBudgetV2,
	serializeContextCacheSnapshot,
} from "./core/context-budget-governor-v2.ts";
export {
	computeReservedTokenBudget,
	estimateToolResultReserve,
	ReservedTokenBudgetError,
	type ReservedTokenBudgetInput,
	type ReservedTokenBudgetResult,
	type ToolResultReserveRequest,
} from "./core/context-budget-reserved-tokens.ts";
export { createEventBus, type EventBus, type EventBusController } from "./core/event-bus.ts";
// Extension system
export type {
	AgentEndEvent,
	AgentStartEvent,
	AgentToolResult,
	AgentToolUpdateCallback,
	AppKeybinding,
	AutocompleteProviderFactory,
	BashToolCallEvent,
	BeforeAgentStartEvent,
	BeforeAgentStartEventResult,
	BeforeProviderRequestEvent,
	BeforeProviderRequestEventResult,
	BuildSystemPromptOptions,
	CompactOptions,
	ContextEvent,
	ContextUsage,
	CustomToolCallEvent,
	EditToolCallEvent,
	ExecOptions,
	ExecResult,
	Extension,
	ExtensionActions,
	ExtensionAPI,
	ExtensionCommandContext,
	ExtensionCommandContextActions,
	ExtensionContext,
	ExtensionContextActions,
	ExtensionError,
	ExtensionEvent,
	ExtensionFactory,
	ExtensionFlag,
	ExtensionHandler,
	ExtensionRuntime,
	ExtensionShortcut,
	ExtensionUIContext,
	ExtensionUIDialogOptions,
	ExtensionWidgetOptions,
	FindToolCallEvent,
	GrepToolCallEvent,
	InputEvent,
	InputEventResult,
	InputSource,
	KeybindingsManager,
	LoadExtensionsResult,
	LsToolCallEvent,
	MessageRenderer,
	MessageRenderOptions,
	ProviderConfig,
	ProviderModelConfig,
	ReadToolCallEvent,
	RegisteredCommand,
	RegisteredTool,
	ResolvedCommand,
	SessionBeforeCompactEvent,
	SessionBeforeForkEvent,
	SessionBeforeSwitchEvent,
	SessionBeforeTreeEvent,
	SessionCompactEvent,
	SessionShutdownEvent,
	SessionStartEvent,
	SessionTreeEvent,
	SlashCommandInfo,
	SlashCommandSource,
	SourceInfo,
	TerminalInputHandler,
	ToolCallEvent,
	ToolCallEventResult,
	ToolDefinition,
	ToolExecutionMode,
	ToolInfo,
	ToolRenderResultOptions,
	ToolResultEvent,
	TurnEndEvent,
	TurnStartEvent,
	UserBashEvent,
	UserBashEventResult,
	WidgetPlacement,
	WorkingIndicatorOptions,
	WriteToolCallEvent,
} from "./core/extensions/index.ts";
export {
	createExtensionRuntime,
	defineTool,
	discoverAndLoadExtensions,
	ExtensionRunner,
	isBashToolResult,
	isEditToolResult,
	isFindToolResult,
	isGrepToolResult,
	isLsToolResult,
	isReadToolResult,
	isToolCallEventType,
	isWriteToolResult,
	wrapRegisteredTool,
	wrapRegisteredTools,
} from "./core/extensions/index.ts";
// Footer data provider (git branch + extension statuses - data not otherwise available to extensions)
export type { ReadonlyFooterDataProvider } from "./core/footer-data-provider.ts";
export { convertToLlm } from "./core/messages.ts";
export { ModelRegistry } from "./core/model-registry.ts";
export type {
	PackageManager,
	PathMetadata,
	ProgressCallback,
	ProgressEvent,
	ResolvedPaths,
	ResolvedResource,
} from "./core/package-manager.ts";
export { DefaultPackageManager } from "./core/package-manager.ts";
export type { ResourceCollision, ResourceDiagnostic, ResourceLoader } from "./core/resource-loader.ts";
export { DefaultResourceLoader, loadProjectContextFiles } from "./core/resource-loader.ts";
export {
	extractReverseSkillFactsFromMarkdown,
	formatReverseSkillFromSource,
	formatReverseSkillMarkdown,
	formatReverseSkillRouteDecision,
	getReverseSkillToolAliases,
	normalizeReverseSkillName,
	normalizeReverseSkillText,
	planReverseSkillToolChecks,
	REVERSE_SKILL_ROUTES,
	type ReverseSkillPlatform,
	type ReverseSkillRisk,
	type ReverseSkillRoute,
	type ReverseSkillRouteDecision,
	type ReverseSkillRouteInput,
	type ReverseSkillRouteScore,
	type ReverseSkillSourceFacts,
	type ReverseSkillSourceInput,
	type ReverseSkillSpecInput,
	routeReverseSkill,
} from "./core/reverse-skill.ts";
export {
	appendRunJournalRecordDurably,
	type OpenRunJournalStoreOptions,
	type RunJournalQuarantineReport,
	RunJournalStore,
	RunJournalStoreCorruptionError,
	writeQuarantineBytesDurably,
} from "./core/run-journal-store.ts";
// SDK for programmatic usage
export {
	AgentSessionRuntime,
	type AgentSessionRuntimeDiagnostic,
	type AgentSessionServices,
	type CreateAgentSessionFromServicesOptions,
	type CreateAgentSessionOptions,
	type CreateAgentSessionResult,
	type CreateAgentSessionRuntimeFactory,
	type CreateAgentSessionRuntimeResult,
	type CreateAgentSessionServicesOptions,
	// Factory
	createAgentSession,
	createAgentSessionFromServices,
	createAgentSessionRuntime,
	createAgentSessionServices,
	createBashTool,
	// Tool factories (for custom cwd)
	createCodingTools,
	createEditTool,
	createFindTool,
	createGrepTool,
	createLsTool,
	createReadOnlyTools,
	createReadTool,
	createWriteTool,
	type PromptTemplate,
} from "./core/sdk.ts";
export {
	type BranchSummaryEntry,
	buildSessionContext,
	type CompactionEntry,
	type CompactionProvenanceDetails,
	CURRENT_SESSION_VERSION,
	type CustomEntry,
	type CustomMessageEntry,
	type FileEntry,
	getLatestCompactionEntry,
	type ModelChangeEntry,
	migrateSessionEntries,
	type NewSessionOptions,
	parseSessionEntries,
	type SessionContext,
	type SessionEntry,
	type SessionEntryBase,
	type SessionHeader,
	type SessionInfo,
	type SessionInfoEntry,
	SessionManager,
	type SessionMessageEntry,
	type SessionQuarantineReport,
	type ThinkingLevelChangeEntry,
} from "./core/session-manager.ts";
export {
	classifySessionTermination,
	formatSessionTermination,
	type SessionTermination,
	type SessionTerminationCause,
	SessionTerminationError,
	type SessionTerminationKind,
} from "./core/session-termination.ts";
export {
	type AgentRuntimeSettings,
	type CompactionSettings,
	type ImageSettings,
	type PackageSource,
	type RetrySettings,
	SettingsManager,
	type ToolSchedulerSetting,
} from "./core/settings-manager.ts";
// Skills
export {
	formatSkillsForPrompt,
	type LoadSkillsFromDirOptions,
	type LoadSkillsResult,
	loadSkills,
	loadSkillsFromDir,
	type Skill,
	type SkillFrontmatter,
} from "./core/skills.ts";
export { createSyntheticSourceInfo } from "./core/source-info.ts";
// Tools
export {
	type BashOperations,
	type BashSpawnContext,
	type BashSpawnHook,
	type BashToolDetails,
	type BashToolInput,
	type BashToolOptions,
	createBashToolDefinition,
	createEditToolDefinition,
	createFindToolDefinition,
	createGrepToolDefinition,
	createLocalBashOperations,
	createLsToolDefinition,
	createReadToolDefinition,
	createWriteToolDefinition,
	DEFAULT_MAX_BYTES,
	DEFAULT_MAX_LINES,
	type EditOperations,
	type EditToolDetails,
	type EditToolInput,
	type EditToolOptions,
	type FindOperations,
	type FindToolDetails,
	type FindToolInput,
	type FindToolOptions,
	formatSize,
	type GrepOperations,
	type GrepToolDetails,
	type GrepToolInput,
	type GrepToolOptions,
	type LsOperations,
	type LsToolDetails,
	type LsToolInput,
	type LsToolOptions,
	type ReadOperations,
	type ReadToolDetails,
	type ReadToolInput,
	type ReadToolOptions,
	type ToolsOptions,
	type TruncationOptions,
	type TruncationResult,
	truncateHead,
	truncateLine,
	truncateTail,
	type WriteOperations,
	type WriteToolInput,
	type WriteToolOptions,
	withFileMutationQueue,
} from "./core/tools/index.ts";
export {
	executeVerifiedBash,
	executeVerifiedLocalBash,
	VERIFIED_BASH_REDACTION_POLICY_ID,
	VerifiedBashAdapterError,
	type VerifiedBashExecutionRequest,
	type VerifiedLocalBashExecutionRequest,
} from "./core/verified-bash-adapter.ts";
// Execution-bound evidence
export {
	type CommandHmacBinder,
	CommandRedactionError,
	createCommandHmacBinder,
	EVIDENCE_COMMAND_REDACTION_POLICY_ID,
	MAX_COMMAND_REDACTION_PLACEHOLDERS,
	parseCommandHmacBinding,
	parseCommandRedactionSummary,
	type RedactedCommandDescriptor,
	redactCommandDescriptor,
} from "./guardrails/command-redaction.ts";
export {
	computeEvidenceCommandSha256,
	computeEvidenceReceiptCoreSha256,
	constantTimeSha256Equal,
	createEvidenceReceipt,
	evidenceReceiptReplayPayload,
	isSafeEvidenceReceiptId,
	isSha256Hex,
	parseEvidenceReceipt,
	parseSha256Hex,
	validateEvidenceReceipt,
	withEvidenceReceiptEnvelope,
} from "./guardrails/evidence-receipt.ts";
export {
	EvidenceReceiptStore,
	type EvidenceReceiptStoreFaultStage,
	type EvidenceReceiptStoreOptions,
} from "./guardrails/evidence-receipt-store.ts";
export {
	EvidenceGate,
	type EvidenceGateOptions,
	FailClosedMergeGate,
	latestRelevantWorkspaceMutationSeq,
	ReplayLedgerManager,
	TaskContractBuilder,
} from "./guardrails/evidence-system.ts";
export {
	type VerifiedEvidenceExecutionOutcome,
	type VerifiedEvidenceExecutionRequest,
	type VerifiedEvidenceExecutionResult,
	VerifiedEvidenceExecutor,
	VerifiedEvidenceExecutorError,
	type VerifiedEvidenceExecutorOptions,
	type VerifiedEvidenceMetadata,
} from "./guardrails/verified-executor.ts";
export {
	captureWorkspaceFingerprint,
	computeGitWorkspaceDirtySha256,
	computeGitWorkspaceManifestSha256,
	computeWorkspaceManifestSha256,
	parseWorkspaceFingerprint,
} from "./guardrails/workspace-fingerprint.ts";
// Main entry point
export { type MainOptions, main } from "./main.ts";
// Run modes for programmatic SDK usage
export {
	InteractiveMode,
	type InteractiveModeOptions,
	type ModelInfo,
	type PrintModeOptions,
	RpcClient,
	type RpcClientOptions,
	type RpcCommand,
	type RpcEventListener,
	type RpcResponse,
	type RpcSessionState,
	runPrintMode,
	runRpcMode,
} from "./modes/index.ts";
// UI components for extensions
export {
	ArminComponent,
	AssistantMessageComponent,
	BashExecutionComponent,
	BorderedLoader,
	BranchSummaryMessageComponent,
	CompactionSummaryMessageComponent,
	CustomEditor,
	CustomMessageComponent,
	DynamicBorder,
	ExtensionEditorComponent,
	ExtensionInputComponent,
	ExtensionSelectorComponent,
	FooterComponent,
	keyHint,
	keyText,
	LoginDialogComponent,
	ModelSelectorComponent,
	OAuthSelectorComponent,
	type RenderDiffOptions,
	rawKeyHint,
	renderDiff,
	SessionSelectorComponent,
	type SettingsCallbacks,
	type SettingsConfig,
	SettingsSelectorComponent,
	ShowImagesSelectorComponent,
	SkillInvocationMessageComponent,
	ThemeSelectorComponent,
	ThinkingSelectorComponent,
	ToolExecutionComponent,
	type ToolExecutionOptions,
	TreeSelectorComponent,
	truncateToVisualLines,
	UserMessageComponent,
	UserMessageSelectorComponent,
	type VisualTruncateResult,
} from "./modes/interactive/components/index.ts";
// Theme utilities for custom tools and extensions
export {
	getLanguageFromPath,
	getMarkdownTheme,
	getSelectListTheme,
	getSettingsListTheme,
	highlightCode,
	initTheme,
	Theme,
	type ThemeColor,
} from "./modes/interactive/theme/theme.ts";
export type {
	ArtifactSetWorkspaceFingerprint,
	ArtifactState,
	CommandHmacBinding,
	CommandRedactionPlaceholder,
	CommandRedactionPlaceholderType,
	CommandRedactionSummary,
	EvidenceCommandDescriptor,
	EvidenceExecutor,
	EvidenceItem,
	EvidenceReceipt,
	EvidenceReceiptDisposition,
	EvidenceReceiptLedgerBinding,
	EvidenceReceiptMode,
	FileArtifactState,
	GitWorkspaceFingerprint,
	GitWorkspaceState,
	MissingArtifactState,
	ReplayEvent,
	ReplayEventType,
	Sha256Hex,
	TaskContract,
	WorkspaceFingerprint,
	WorkspaceMutationReplayPayload,
	WorkspaceScope,
} from "./types/evidence.ts";
// Clipboard utilities
export { copyToClipboard } from "./utils/clipboard.ts";
export { parseFrontmatter, stripFrontmatter } from "./utils/frontmatter.ts";
export { convertToPng } from "./utils/image-convert.ts";
export { formatDimensionNote, type ResizedImage, resizeImage } from "./utils/image-resize.ts";
// Shell utilities
export { getShellConfig } from "./utils/shell.ts";
