// Core session management

export { type Args, parseArgs } from "./cli/args.ts";

// Config paths
export { CONFIG_DIR_NAME, getAgentDir, VERSION } from "./config.ts";
export {
	AgentSession,
	type AgentSessionConfig,
	type AgentSessionEvent,
	type AgentSessionEventListener,
	type ModelCycleResult,
	type ParsedSkillBlock,
	type PromptOptions,
	parseSkillBlock,
	type SessionStats,
} from "./core/agent-session.ts";
// Auth and model registry
export {
	type ApiKeyCredential,
	type AuthCredential,
	type AuthStatus,
	AuthStorage,
	type AuthStorageBackend,
	FileAuthStorageBackend,
	InMemoryAuthStorageBackend,
	type OAuthCredential,
} from "./core/auth-storage.ts";
// Compaction
export {
	type BranchPreparation,
	type BranchSummaryResult,
	type CollectEntriesResult,
	type CompactionResult,
	type CutPointResult,
	calculateContextTokens,
	collectEntriesForBranchSummary,
	compact,
	DEFAULT_COMPACTION_SETTINGS,
	estimateTokens,
	type FileOperations,
	findCutPoint,
	findTurnStartIndex,
	type GenerateBranchSummaryOptions,
	generateBranchSummary,
	generateSummary,
	getLastAssistantUsage,
	prepareBranchEntries,
	serializeConversation,
	shouldCompact,
} from "./core/compaction/index.ts";
export {
	type CompactStackProfile,
	type CompactStackRecommendation,
	classifyContextPackageRole,
	type ExternalContextPackageRegistration,
	type ExternalContextPackageRole,
	type ExternalPrunerLicense,
	type ExternalPrunerMode,
	type ExternalPrunerRegistration,
	type ExternalSessionCompactorRegistration,
	getRecommendedCompactStack,
	getRecommendedPrunerDefaults,
	getRecommendedSessionCompactorDefaults,
	type NeverPruneTarget,
	type PrunerRecommendedDefaults,
	type PrunerTrigger,
	registerExternalPrunerOwner,
	type SessionCompactorPhase,
	type SessionCompactorRecommendedDefaults,
	type SessionCompactorTrigger,
	type ValidatedCompactPackageStack,
	type ValidatedExternalPrunerOwner,
	type ValidatedSessionCompactorOwner,
	validateCompactPackageStack,
	validateSingleExternalPrunerOwner,
	validateSingleSessionCompactorOwner,
} from "./core/compaction/pruner-policy.ts";
export * from "./core/context-graph-identity-resolution.ts";
export * from "./core/context-graph-memory-store.ts";
export * from "./core/context-graph-ontology-generation.ts";
export * from "./core/context-graph-ontology-registry.ts";
export {
	type ContextGraphAdoptionDecision,
	type ContextGraphAdoptionInput,
	type ContextGraphAdoptionReason,
	type ContextGraphLibraryCategory,
	type ContextGraphLibraryClassification,
	type ContextGraphProfile,
	type ContextGraphStackRecommendation,
	type ContextGraphVerdict,
	classifyContextGraphLibrary,
	getContextGraphToolSurface,
	getRecommendedContextGraphStack,
	getUnderstandAnythingIndexPlan,
	type MemoryFactCategory,
	type MemoryFactPolicyCandidate,
	type MemoryFactPolicyDecision,
	type MemoryFactPolicyReason,
	type Neo4jAdoptionCondition,
	type UnderstandAnythingIndexPlan,
	validateContextGraphAdoption,
	validateMemoryFactPolicy,
} from "./core/context-graph-policy.ts";
export * from "./core/context-graph-reasoning.ts";
export * from "./core/context-graph-retrieval.ts";
export { createEventBus, type EventBus, type EventBusController } from "./core/event-bus.ts";
export {
	canCacheToolResult,
	canonicalizeJson,
	classifyToolResultCacheEligibility,
	createExactResponseCacheKey,
	createToolResultCacheKey,
	EXACT_CACHE_KEY_VERSION,
	type ExactResponseCacheKey,
	type ExactResponseCacheKeyInput,
	type ExactResponseCacheKeyMaterial,
	hashCanonicalJson,
	isBashToolName,
	isKnownMutatingToolName,
	type JsonObject,
	type JsonPrimitive,
	type JsonValue,
	MUTATING_TOOL_NAME_TERMS,
	type ToolResultCacheKey,
	type ToolResultCacheKeyInput,
	type ToolResultCacheKeyMaterial,
	type ToolResultCachePolicyCandidate,
	type ToolResultCachePolicyDecision,
	type ToolResultCachePolicyReason,
	type ToolResultCacheStatus,
} from "./core/exact-cache-policy.ts";
// Extension system
export type {
	AgentEndEvent,
	AgentStartEvent,
	AgentToolResult,
	AgentToolUpdateCallback,
	AppKeybinding,
	AutocompleteProviderFactory,
	BashToolCallEvent,
	BeforeAgentStartEvent,
	BeforeAgentStartEventResult,
	BeforeProviderRequestEvent,
	BeforeProviderRequestEventResult,
	BuildSystemPromptOptions,
	CompactOptions,
	ContextEvent,
	ContextUsage,
	CustomToolCallEvent,
	EditToolCallEvent,
	ExecOptions,
	ExecResult,
	Extension,
	ExtensionActions,
	ExtensionAPI,
	ExtensionCommandContext,
	ExtensionCommandContextActions,
	ExtensionContext,
	ExtensionContextActions,
	ExtensionError,
	ExtensionEvent,
	ExtensionFactory,
	ExtensionFlag,
	ExtensionHandler,
	ExtensionRuntime,
	ExtensionShortcut,
	ExtensionUIContext,
	ExtensionUIDialogOptions,
	ExtensionWidgetOptions,
	FindToolCallEvent,
	GrepToolCallEvent,
	InputEvent,
	InputEventResult,
	InputSource,
	KeybindingsManager,
	LoadExtensionsResult,
	LsToolCallEvent,
	MessageRenderer,
	MessageRenderOptions,
	ProviderConfig,
	ProviderModelConfig,
	ReadToolCallEvent,
	RegisteredCommand,
	RegisteredTool,
	ResolvedCommand,
	SessionBeforeCompactEvent,
	SessionBeforeForkEvent,
	SessionBeforeSwitchEvent,
	SessionBeforeTreeEvent,
	SessionCompactEvent,
	SessionShutdownEvent,
	SessionStartEvent,
	SessionTreeEvent,
	SlashCommandInfo,
	SlashCommandSource,
	SourceInfo,
	TerminalInputHandler,
	ToolCallEvent,
	ToolCallEventResult,
	ToolDefinition,
	ToolExecutionMode,
	ToolInfo,
	ToolRenderResultOptions,
	ToolResultEvent,
	TurnEndEvent,
	TurnStartEvent,
	UserBashEvent,
	UserBashEventResult,
	WidgetPlacement,
	WorkingIndicatorOptions,
	WriteToolCallEvent,
} from "./core/extensions/index.ts";
export {
	createExtensionRuntime,
	defineTool,
	discoverAndLoadExtensions,
	ExtensionRunner,
	isBashToolResult,
	isEditToolResult,
	isFindToolResult,
	isGrepToolResult,
	isLsToolResult,
	isReadToolResult,
	isToolCallEventType,
	isWriteToolResult,
	wrapRegisteredTool,
	wrapRegisteredTools,
} from "./core/extensions/index.ts";
// Footer data provider (git branch + extension statuses - data not otherwise available to extensions)
export type { ReadonlyFooterDataProvider } from "./core/footer-data-provider.ts";
export {
	createHeadroomBeforeProviderSend,
	type HeadroomBeforeProviderSend,
	type HeadroomBeforeProviderSendOptions,
	type HeadroomBeforeProviderSendStats,
	type HeadroomCompressText,
	type HeadroomCompressTextInput,
} from "./core/headroom-middleware.ts";
export {
	createLeanContextBeforeProviderSend,
	type LeanContextBeforeProviderSend,
	type LeanContextBeforeProviderSendOptions,
} from "./core/lean-context-middleware.ts";
export {
	createLeanContextPolicyState,
	decideLeanContextEmission,
	formatLeanContextUnchangedStub,
	getLeanContextTrackingHash,
	LEAN_CONTEXT_DEFAULT_MIN_STUB_TOKENS,
	LEAN_CONTEXT_NEVER_STUB_FILENAMES,
	type LeanContextDecisionReason,
	type LeanContextEmission,
	type LeanContextPolicyDecision,
	type LeanContextPolicyInput,
	type LeanContextPolicyOptions,
	type LeanContextPolicyState,
} from "./core/lean-context-policy.ts";
export { convertToLlm } from "./core/messages.ts";
export { ModelRegistry } from "./core/model-registry.ts";
export * from "./core/native-adoption-benchmark.ts";
export {
	type CompositionConflict,
	type CompositionInput,
	type CompositionPromotionRecord,
	type CompositionResourceFilter,
	type CompositionReview,
	type CompositionSurface,
	type CompositionVerdict,
	checkCapabilitySurfaceMatch,
	checkOmkDomainMutation,
	checkSingleSurfaceOwner,
	composeCandidateBatch,
	composePackage,
	createDefaultCompositionPolicy,
	createPromotionRecord,
	inferRequestedSurfaces,
	type OmkOwnedDomain,
	type PackageCompositionPolicy,
	resolveResourceFilter,
	type SurfaceOwnerRule,
	toPackageSource,
} from "./core/package-composition.ts";
export type {
	PackageManager,
	PathMetadata,
	ProgressCallback,
	ProgressEvent,
	ResolvedPaths,
	ResolvedResource,
} from "./core/package-manager.ts";
export { DefaultPackageManager } from "./core/package-manager.ts";
export type { ContextFile, ResourceCollision, ResourceDiagnostic, ResourceLoader } from "./core/resource-loader.ts";
export { DefaultResourceLoader, loadProjectContextFiles, sanitizeContextForJailbreak } from "./core/resource-loader.ts";
// SDK for programmatic usage
export {
	AgentSessionRuntime,
	type AgentSessionRuntimeDiagnostic,
	type AgentSessionServices,
	type CreateAgentSessionFromServicesOptions,
	type CreateAgentSessionOptions,
	type CreateAgentSessionResult,
	type CreateAgentSessionRuntimeFactory,
	type CreateAgentSessionRuntimeResult,
	type CreateAgentSessionServicesOptions,
	// Factory
	createAgentSession,
	createAgentSessionFromServices,
	createAgentSessionRuntime,
	createAgentSessionServices,
	createBashTool,
	// Tool factories (for custom cwd)
	createCodingTools,
	createEditTool,
	createFindTool,
	createGrepTool,
	createLsTool,
	createReadOnlyTools,
	createReadTool,
	createWriteTool,
	type PromptTemplate,
} from "./core/sdk.ts";
export {
	ALLOWED_SEMANTIC_CACHE_TASK_CLASSES,
	classifySemanticCacheEligibility,
	FORBIDDEN_SEMANTIC_CACHE_ACTION_TERMS,
	FORBIDDEN_SEMANTIC_CACHE_TASK_CLASS_TERMS,
	type SemanticCacheAttributePolicyReason,
	type SemanticCacheAttributeValidation,
	type SemanticCacheCandidate,
	type SemanticCacheContextAttributes,
	type SemanticCacheDependencyFlags,
	type SemanticCachePolicyDecision,
	type SemanticCachePolicyReason,
	type SemanticCacheResponseKind,
	type SemanticCacheTaskClass,
	validateSemanticCacheAttributes,
} from "./core/semantic-cache-policy.ts";
export {
	type BranchSummaryEntry,
	buildSessionContext,
	type CompactionEntry,
	CURRENT_SESSION_VERSION,
	type CustomEntry,
	type CustomMessageEntry,
	type FileEntry,
	getLatestCompactionEntry,
	type ModelChangeEntry,
	migrateSessionEntries,
	type NewSessionOptions,
	parseSessionEntries,
	type SessionContext,
	type SessionEntry,
	type SessionEntryBase,
	type SessionHeader,
	type SessionInfo,
	type SessionInfoEntry,
	SessionManager,
	type SessionMessageEntry,
	type ThinkingLevelChangeEntry,
} from "./core/session-manager.ts";
export {
	type CompactionSettings,
	type ImageSettings,
	type PackageSource,
	type RetrySettings,
	SettingsManager,
} from "./core/settings-manager.ts";
// Skills
export {
	formatSkillsForPrompt,
	type LoadSkillsFromDirOptions,
	type LoadSkillsResult,
	loadSkills,
	loadSkillsFromDir,
	type Skill,
	type SkillFrontmatter,
} from "./core/skills.ts";
export { createSyntheticSourceInfo } from "./core/source-info.ts";
// Tools
export {
	type BashOperations,
	type BashSandboxPreflight,
	type BashSpawnContext,
	type BashSpawnHook,
	type BashToolDetails,
	type BashToolInput,
	type BashToolOptions,
	createBashToolDefinition,
	createEditToolDefinition,
	createFindToolDefinition,
	createGrepToolDefinition,
	createLocalBashOperations,
	createLsToolDefinition,
	createReadToolDefinition,
	createWriteToolDefinition,
	DEFAULT_MAX_BYTES,
	DEFAULT_MAX_LINES,
	type EditOperations,
	type EditToolDetails,
	type EditToolInput,
	type EditToolOptions,
	type FindOperations,
	type FindToolDetails,
	type FindToolInput,
	type FindToolOptions,
	formatSize,
	type GrepOperations,
	type GrepToolDetails,
	type GrepToolInput,
	type GrepToolOptions,
	type LsOperations,
	type LsToolDetails,
	type LsToolInput,
	type LsToolOptions,
	type ReadOperations,
	type ReadToolDetails,
	type ReadToolInput,
	type ReadToolOptions,
	type ToolsOptions,
	type TruncationOptions,
	type TruncationResult,
	truncateHead,
	truncateLine,
	truncateTail,
	type WriteOperations,
	type WriteToolInput,
	type WriteToolOptions,
	withFileMutationQueue,
} from "./core/tools/index.ts";
// Main entry point
export { type MainOptions, main } from "./main.ts";
// Run modes for programmatic SDK usage
export {
	InteractiveMode,
	type InteractiveModeOptions,
	type ModelInfo,
	type PrintModeOptions,
	RpcClient,
	type RpcClientOptions,
	type RpcCommand,
	type RpcEventListener,
	type RpcResponse,
	type RpcSessionState,
	runPrintMode,
	runRpcMode,
} from "./modes/index.ts";
// UI components for extensions
export {
	ArminComponent,
	AssistantMessageComponent,
	BashExecutionComponent,
	BorderedLoader,
	BranchSummaryMessageComponent,
	CompactionSummaryMessageComponent,
	CustomEditor,
	CustomMessageComponent,
	DynamicBorder,
	ExtensionEditorComponent,
	ExtensionInputComponent,
	ExtensionSelectorComponent,
	FooterComponent,
	keyHint,
	keyText,
	LoginDialogComponent,
	ModelSelectorComponent,
	OAuthSelectorComponent,
	type RenderDiffOptions,
	rawKeyHint,
	renderDiff,
	SessionSelectorComponent,
	type SettingsCallbacks,
	type SettingsConfig,
	SettingsSelectorComponent,
	ShowImagesSelectorComponent,
	SkillInvocationMessageComponent,
	ThemeSelectorComponent,
	ThinkingSelectorComponent,
	ToolExecutionComponent,
	type ToolExecutionOptions,
	TreeSelectorComponent,
	truncateToVisualLines,
	UserMessageComponent,
	UserMessageSelectorComponent,
	type VisualTruncateResult,
} from "./modes/interactive/components/index.ts";
// Theme utilities for custom tools and extensions
export {
	getLanguageFromPath,
	getMarkdownTheme,
	getSelectListTheme,
	getSettingsListTheme,
	highlightCode,
	initTheme,
	Theme,
	type ThemeColor,
} from "./modes/interactive/theme/theme.ts";
// Clipboard utilities
export { copyToClipboard } from "./utils/clipboard.ts";
export { parseFrontmatter, stripFrontmatter } from "./utils/frontmatter.ts";
export { convertToPng } from "./utils/image-convert.ts";
export { formatDimensionNote, type ResizedImage, resizeImage } from "./utils/image-resize.ts";
// Shell utilities
export { getShellConfig } from "./utils/shell.ts";
