#!/usr/bin/env node
// Regenerates references/index.md from the vendored corpus.
// Run after refreshing corpus/:  node scripts/build-index.mjs

import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative, dirname, extname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SKILL_ROOT = resolve(__dirname, "..");
const CORPUS = join(SKILL_ROOT, "corpus");
const OUT = join(SKILL_ROOT, "references", "index.md");

const VENDOR_META = {
  Anthropic: { blurb: "Claude family (Opus/Sonnet/Haiku), Claude Code, Cowork, official published prompts." },
  OpenAI: { blurb: "ChatGPT / GPT-5.x, Codex CLI, o-series reasoning, tools (web/deep research/python/canvas/image/memory)." },
  Google: { blurb: "Gemini 3.x/2.5, Gemini CLI, Antigravity, Jules, NotebookLM, AI Studio." },
  xAI: { blurb: "Grok 4.x, Grok Build CLI agent, Grok Expert, personas, safety instructions." },
  Microsoft: { blurb: "GitHub Copilot, VS Code Copilot Agent, Copilot CLI, Copilot in Word, macOS app." },
  Perplexity: { blurb: "Perplexity Computer, Deep Research, Comet Browser, Voice Assistant." },
  Cursor: { blurb: "Cursor IDE agent." },
  Meta: { blurb: "Meta AI / Muse Spark." },
  Mistral: { blurb: "Mistral Medium 3.5 (Vibe), Mistral Code." },
  Kimi: { blurb: "Moonshot Kimi K2.6." },
  DeepSeek: { blurb: "chat.deepseek.com." },
  GLM: { blurb: "Zhipu GLM." },
  Qwen: { blurb: "Alibaba Qwen 3.6 Plus." },
  Notion: { blurb: "Notion AI." },
  Misc: { blurb: "Community & third-party: Warp, Zed, Amp, Docker Gordon, ElevenLabs, Raycast, Kagi, and more." },
};

function listFiles(dir, acc = []) {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) listFiles(full, acc);
    else if (entry.isFile()) {
      const ext = extname(entry.name).toLowerCase();
      if (ext === ".md" || ext === ".txt" || ext === ".xml") acc.push(full);
    }
  }
  return acc;
}

function vendorOf(p) {
  return relative(CORPUS, p).split(/[\\/]/)[0];
}

function firstHeading(p) {
  try {
    for (const line of readFileSync(p, "utf8").split(/\r?\n/)) {
      const t = line.trim();
      if (!t) continue;
      if (t.startsWith("#")) return t.replace(/^#+\s*/, "").slice(0, 100);
      return t.slice(0, 100);
    }
  } catch {}
  return "";
}

function humanBytes(n) {
  if (n < 1024) return `${n}B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(0)}K`;
  return `${(n / (1024 * 1024)).toFixed(1)}M`;
}

const files = listFiles(CORPUS).sort();
const byVendor = new Map();
for (const f of files) {
  const v = vendorOf(f);
  if (!byVendor.has(v)) byVendor.set(v, []);
  byVendor.get(v).push(f);
}
const vendors = [...byVendor.keys()].sort((a, b) => byVendor.get(b).length - byVendor.get(a).length);

const lines = [];
lines.push("# system-prompts-leaks — corpus index");
lines.push("");
lines.push("> Auto-generated by `scripts/build-index.mjs`. Do not edit by hand; re-run after refreshing `corpus/`.");
lines.push("");
lines.push(`- **Files:** ${files.length}`);
lines.push(`- **Vendors:** ${vendors.length}`);
lines.push("");
lines.push("Use `scripts/search.mjs` to locate entries. All paths below are relative to the skill root.");
lines.push("");
lines.push("| Vendor | Files | Coverage |");
lines.push("| --- | ---: | --- |");
for (const v of vendors) {
  const blurb = (VENDOR_META[v] && VENDOR_META[v].blurb) || "";
  lines.push(`| **${v}** | ${byVendor.get(v).length} | ${blurb} |`);
}
lines.push("");
lines.push("---");
lines.push("");

for (const v of vendors) {
  lines.push(`## ${v} (${byVendor.get(v).length})`);
  if (VENDOR_META[v]) lines.push("");
  for (const f of byVendor.get(v)) {
    const rel = relative(SKILL_ROOT, f);
    const head = firstHeading(f);
    const size = humanBytes(statSync(f).size);
    const tail = head ? ` &mdash; _${head}_` : "";
    lines.push(`- [${rel}](${rel}) (${size})${tail}`);
  }
  lines.push("");
}

writeFileSync(OUT, lines.join("\n"));
console.log(`Wrote ${OUT} (${files.length} files, ${vendors.length} vendors)`);
