/**
 * Domain profiles for the deterministic capability router. Each profile classifies
 * an agent by name+description keywords and offers a catalog-verified skill pool
 * plus typical MCP/hook defaults. Generated from the domain analysis (19 domains,
 * 491 verified skills).
 */

/** A capability-routing domain profile. Keywords classify an agent by name+description. */
export interface DomainProfile {
	/** Stable lowercase id, e.g. "security". */
	readonly id: string;
	/** Human-readable label, e.g. "Security & Compliance". */
	readonly label: string;
	/** Classification patterns, tested against `${name} ${description}` lowercased. First match wins. */
	readonly keywords: readonly RegExp[];
	/** Candidate skill names (lowercase, already catalog-verified). */
	readonly skillPool: readonly string[];
	/** Typical MCP servers for this domain. */
	readonly defaultMcp: readonly string[];
	/** Typical hooks for this domain. */
	readonly defaultHooks: readonly string[];
}

/** All domain profiles, ordered so that more specific domains precede general ones. */
export const DOMAIN_PROFILES: readonly DomainProfile[] = [
	{
		id: "frontend-web",
		label: "Frontend & Web",
		keywords: [
			/react/i,
			/vue/i,
			/angular/i,
			/svelte/i,
			/next.?js/i,
			/nextjs/i,
			/frontend/i,
			/css/i,
			/tailwind/i,
			/ui-?design/i,
			/web-?component/i,
			/html/i,
			/jamstack/i,
			/gatsby/i,
			/remix/i,
			/astro/i,
			/solid-?js/i,
			/qwik/i,
			/visual-?storyteller/i,
			/inclusive-?visual/i,
		],
		skillPool: [
			"react-patterns",
			"react-performance",
			"react-testing",
			"vercel-react-best-practices",
			"vercel-composition-patterns",
			"next-best-practices",
			"next-cache-components",
			"next-upgrade",
			"nextjs-turbopack",
			"frontend-patterns",
			"frontend-a11y",
			"frontend-design",
			"frontend-design-direction",
			"frontend-ui-engineering",
			"vite-patterns",
			"vue-patterns",
			"vue-best-practices",
			"vue-jsx-best-practices",
			"vue-pinia-best-practices",
			"vue-router-best-practices",
			"vue-testing-best-practices",
			"vueuse-functions",
			"vue-debug-guides",
			"vue-options-api-best-practices",
			"angular-developer",
			"svelte-code-writer",
			"design-system",
			"interface-design",
			"canvas-design",
			"accessibility",
			"seo-audit",
			"page-cro",
			"copywriting",
			"content-strategy",
		],
		defaultMcp: ["filesystem", "context7", "playwright"],
		defaultHooks: ["pre-shell-guard", "protect-secrets", "typecheck-after-edit", "eslint-after-edit"],
	},
	{
		id: "backend-api",
		label: "Backend & API",
		keywords: [
			/backend/i,
			/api-?design/i,
			/graphql/i,
			/grpc/i,
			/microservice/i,
			/rest-?api/i,
			/nodejs/i,
			/nest.?js/i,
			/express/i,
			/django/i,
			/flask/i,
			/fastapi/i,
			/spring.?boot/i,
			/rails/i,
			/laravel/i,
			/gin/i,
			/fiber/i,
			/api-?tester/i,
			/mcp-?build/i,
			/mcp-?server/i,
			/agents-?orchestrat/i,
			/multi-?agent-?system/i,
			/autonomous-?optim/i,
			/identity-?graph/i,
			/aeo-?foundations/i,
			/workflow-?architect/i,
			/workflow-?optim/i,
			/automation-?govern/i,
			/database-?opt/i,
			/solution-?engineer/i,
			/rest/i,
			/openapi/i,
		],
		skillPool: [
			"backend-patterns",
			"api-design",
			"api-connector-builder",
			"database-migrations",
			"nestjs-patterns",
			"springboot-patterns",
			"springboot-tdd",
			"springboot-security",
			"springboot-verification",
			"django-patterns",
			"django-tdd",
			"django-security",
			"django-verification",
			"django-celery",
			"fastapi-patterns",
			"laravel-patterns",
			"laravel-security",
			"laravel-tdd",
			"laravel-verification",
			"golang-patterns",
			"nestjs-patterns",
			"error-handling",
			"hexagonal-architecture",
			"architecture-decision-records",
			"mcp-builder",
			"mcp-server-patterns",
			"documentation-lookup",
			"security-review",
		],
		defaultMcp: ["filesystem", "context7", "serena"],
		defaultHooks: ["pre-shell-guard", "protect-secrets", "typecheck-after-edit"],
	},
	{
		id: "mobile",
		label: "Mobile",
		keywords: [
			/mobile/i,
			/ios/i,
			/android/i,
			/flutter/i,
			/react-?native/i,
			/kotlin-?mobile/i,
			/swift-?mobile/i,
			/expo/i,
			/app-?store/i,
		],
		skillPool: [
			"react-native-best-practices",
			"dart-flutter-patterns",
			"swiftui-patterns",
			"swiftui-ui-patterns",
			"swift-concurrency-6-2",
			"swift-protocol-di-testing",
			"swift-actor-persistence",
			"android-clean-architecture",
			"compose-multiplatform-patterns",
			"ios-design-review",
			"ios-icon-gen",
			"foundation-models-on-device",
			"liquid-glass-design",
			"kotlin-patterns",
			"kotlin-coroutines-flows",
			"kotlin-ktor-patterns",
			"kotlin-exposed-patterns",
			"kotlin-testing",
		],
		defaultMcp: ["filesystem", "context7"],
		defaultHooks: ["pre-shell-guard", "protect-secrets", "typecheck-after-edit"],
	},
	{
		id: "systems",
		label: "Systems & Low-level",
		keywords: [
			/rust/i,
			/golang/i,
			/go-?developer/i,
			/c-?developer/i,
			/cpp/i,
			/c\+\+/i,
			/zig/i,
			/systems-?program/i,
			/embedded/i,
			/kernel/i,
			/wasm/i,
			/assembly/i,
			/concurrency/i,
			/senior-?develop/i,
			/software-?architect/i,
			/technical-?consultant/i,
			/rapid-?prototyp/i,
			/code-?reviewer/i,
			/git-?workflow/i,
			/filament-?optim/i,
			/lsp-?index/i,
			/minimal-?change/i,
		],
		skillPool: [
			"rust-patterns",
			"rust-testing",
			"golang-patterns",
			"golang-testing",
			"cpp-coding-standards",
			"cpp-testing",
			"property-based-testing",
			"git-workflow",
			"git-master",
			"git-commit",
			"git-create-pr",
			"git-worktrees",
			"ast-grep",
			"lsp",
			"lsp-setup",
			"coding-standards",
			"hexagonal-architecture",
			"review-work",
			"differential-review",
			"understand-anything",
			"packages",
		],
		defaultMcp: ["filesystem", "context7", "serena", "github"],
		defaultHooks: ["pre-shell-guard", "protect-secrets", "typecheck-after-edit"],
	},
	{
		id: "devops-infra",
		label: "DevOps & Infrastructure",
		keywords: [
			/devops/i,
			/sre/i,
			/kubernetes/i,
			/docker/i,
			/terraform/i,
			/ansible/i,
			/ci-?cd/i,
			/jenkins/i,
			/gitlab/i,
			/platform-?eng/i,
			/cloud-?arch/i,
			/aws/i,
			/azure/i,
			/gcp/i,
			/infra/i,
			/reliab/i,
			/terminal-?integ/i,
			/salesforce-?arch/i,
			/feishu/i,
			/it-?service/i,
			/network-?engineer/i,
			/site-?reliab/i,
		],
		skillPool: [
			"docker-patterns",
			"kubernetes-patterns",
			"deployment-patterns",
			"github-ops",
			"database-migrations",
			"production-audit",
			"production-scheduling",
			"workspace-surface-audit",
			"benchmark",
			"canary-watch",
			"dashboard-builder",
			"latency-critical-systems",
			"redis-patterns",
			"postgres-patterns",
			"network-config-validation",
			"network-interface-health",
			"network-bgp-diagnostics",
			"cisco-ios-patterns",
			"netmiko-ssh-automation",
			"homelab-network-setup",
		],
		defaultMcp: ["filesystem", "github", "context7"],
		defaultHooks: ["pre-shell-guard", "protect-secrets", "release-check-before-stop", "npm-audit-summary"],
	},
	{
		id: "security",
		label: "Security & Compliance",
		keywords: [
			/security/i,
			/pentest/i,
			/vulnerab/i,
			/threat/i,
			/forensic/i,
			/bounty/i,
			/reverse/i,
			/malware/i,
			/siem/i,
			/zeroiz/i,
			/defi/i,
			/evm/i,
			/solana/i,
			/cosmos/i,
			/substrate/i,
			/cairo/i,
			/algorand/i,
			/ton-/i,
			/smart-?contract/i,
			/blockchain/i,
			/incident/i,
			/breach/i,
			/red-?team/i,
			/secops/i,
			/identity-?trust/i,
			/zk-?steward/i,
			/penetration/i,
		],
		skillPool: [
			"security-review",
			"security-scan",
			"security-bounty-hunter",
			"differential-review",
			"audit",
			"audit-context-building",
			"audit-prep-assistant",
			"audit-website",
			"codeql",
			"semgrep",
			"semgrep-rule-creator",
			"sarif-parsing",
			"supply-chain-risk-auditor",
			"zeroize-audit",
			"defi-amm-security",
			"evm-token-decimals",
			"nodejs-keccak256",
			"llm-trading-agent-security",
			"yara-rule-authoring",
			"agentic-actions-auditor",
			"variant-analysis",
			"safety-guard",
			"sharp-edges",
			"hipaa-compliance",
			"insecure-defaults",
			"fp-check",
			"dwarf-expert",
			"entry-point-analyzer",
		],
		defaultMcp: ["filesystem", "github", "context7"],
		defaultHooks: ["pre-shell-guard", "protect-secrets", "release-check-before-stop"],
	},
	{
		id: "legal-compliance",
		label: "Legal & Compliance",
		keywords: [
			/legal/i,
			/compliance/i,
			/gdpr/i,
			/privacy/i,
			/contract/i,
			/regulatory/i,
			/hipaa/i,
			/pci/i,
			/soc2/i,
			/grant-?writ/i,
			/esg/i,
			/sustainab/i,
		],
		skillPool: [
			"hipaa-compliance",
			"audit",
			"audit-prep-assistant",
			"sarif-parsing",
			"differential-review",
			"doc-coauthoring",
			"docx",
			"pdf",
			"xlsx",
			"pptx",
			"research-grants",
			"literature-review",
			"brand-voice",
		],
		defaultMcp: ["filesystem", "context7", "memory"],
		defaultHooks: ["protect-secrets", "release-check-before-stop"],
	},
	{
		id: "data-ml",
		label: "Data & ML",
		keywords: [
			/data-?sci/i,
			/data-?eng/i,
			/machine-?learning/i,
			/ai-?engineer/i,
			/deep-?learning/i,
			/pytorch/i,
			/tensorflow/i,
			/nlp/i,
			/computer-?vision/i,
			/mlops/i,
			/etl/i,
			/spark/i,
			/airflow/i,
			/llm/i,
			/model-?qa/i,
			/performance-?bench/i,
			/experiment-?track/i,
			/tool-?evaluator/i,
			/reality-?checker/i,
			/feedback-?synth/i,
			/ai-?data-?remediation/i,
			/data-?consolidation/i,
			/image-?prompt/i,
			/prompt-?engineer/i,
			/test-?results/i,
			/voice-?ai/i,
			/data-?throughput/i,
		],
		skillPool: [
			"pytorch-patterns",
			"pytorch-lightning",
			"scikit-learn",
			"transformers",
			"mle-workflow",
			"ml-adoption-playbook",
			"shap",
			"dask",
			"polars",
			"networkx",
			"statsmodels",
			"pymc",
			"sympy",
			"matplotlib",
			"seaborn",
			"plotly",
			"scientific-visualization",
			"statistical-analysis",
			"data-visualization",
			"property-based-testing",
			"python-patterns",
			"python-testing",
			"cost-aware-llm-pipeline",
			"recsys-pipeline-architect",
			"agent-architecture-audit",
		],
		defaultMcp: ["filesystem", "context7", "serena"],
		defaultHooks: ["pre-shell-guard", "protect-secrets", "typecheck-after-edit"],
	},
	{
		id: "data-finance",
		label: "Finance & Quant",
		keywords: [
			/finance/i,
			/fintech/i,
			/accounting/i,
			/trading/i,
			/quant/i,
			/risk-?analy/i,
			/payment/i,
			/stripe/i,
			/billing/i,
			/tax/i,
			/investment/i,
			/portfolio/i,
			/accounts-?payable/i,
			/bookkeeper/i,
			/cfo/i,
			/financial-?analy/i,
			/fp-?a/i,
			/pricing-?analy/i,
			/loan-?officer/i,
			/pipeline-?analy/i,
			/m-?a-?integration/i,
		],
		skillPool: [
			"finance-billing-ops",
			"customer-billing-ops",
			"postgres-patterns",
			"mysql-patterns",
			"database-migrations",
			"redis-patterns",
			"statsmodels",
			"statistical-analysis",
			"pymc",
			"polars",
			"plotly",
			"seaborn",
			"investor-materials",
			"investor-outreach",
			"supabase",
			"supabase-postgres-best-practices",
			"xlsx",
			"docx",
			"pdf",
			"pptx",
		],
		defaultMcp: ["filesystem", "context7"],
		defaultHooks: ["protect-secrets", "release-check-before-stop"],
	},
	{
		id: "scientific-research",
		label: "Scientific & Academic",
		keywords: [
			/research/i,
			/scien/i,
			/bioinform/i,
			/genom/i,
			/chem/i,
			/physics/i,
			/statistic/i,
			/academic/i,
			/paper/i,
			/citation/i,
			/lab-/i,
			/clinical/i,
			/medical/i,
			/healthcare/i,
			/pubmed/i,
			/patent/i,
			/scholar/i,
		],
		skillPool: [
			"literature-review",
			"scholar-evaluation",
			"scientific-writing",
			"scientific-visualization",
			"scientific-brainstorming",
			"scientific-critical-thinking",
			"hypothesis-generation",
			"research-grants",
			"research-ops",
			"academic-pptx",
			"pubmed-database",
			"arxiv-database",
			"uspto-database",
			"biopython",
			"gget",
			"rdkit",
			"scanpy",
			"clinical-decision-support",
			"healthcare-cdss-patterns",
			"healthcare-emr-patterns",
			"exploratory-data-analysis",
			"deepchem",
			"molecular-dynamics",
		],
		defaultMcp: ["filesystem", "context7", "fetch", "firecrawl"],
		defaultHooks: ["protect-secrets", "session-context"],
	},
	{
		id: "marketing-content",
		label: "Marketing & Content",
		keywords: [
			/marketing/i,
			/content/i,
			/copywrit/i,
			/seo/i,
			/brand/i,
			/growth/i,
			/social/i,
			/email-?sequence/i,
			/email-?intel/i,
			/ad-/i,
			/campaign/i,
			/funnel/i,
			/cro/i,
			/conversion/i,
			/landing/i,
			/newsletter/i,
			/podcast/i,
			/pr-/i,
			/communic/i,
			/instagram/i,
			/twitter/i,
			/tiktok/i,
			/multi-?platform-?publish/i,
			/programmatic-?display/i,
			/sales-?outreach/i,
			/sales-?data/i,
			/sales-?engineer/i,
			/developer-?advocate/i,
			/search-?query/i,
			/tracking-?measure/i,
			/private-?domain/i,
			/x-?twitter/i,
			/analytics-?report/i,
			/behavioral-?nudge/i,
			/paid-?media/i,
			/whimsy/i,
		],
		skillPool: [
			"copywriting",
			"copy-editing",
			"content-strategy",
			"content-engine",
			"seo",
			"seo-audit",
			"schema-markup",
			"programmatic-seo",
			"competitor-alternatives",
			"marketing-ideas",
			"marketing-psychology",
			"marketing-campaign",
			"brand-voice",
			"brand-guidelines",
			"brand-discovery",
			"brandkit",
			"social-content",
			"email-sequence",
			"ab-test-setup",
			"analytics-tracking",
			"launch-strategy",
			"page-cro",
			"popup-cro",
			"form-cro",
			"signup-flow-cro",
			"onboarding-cro",
			"paywall-upgrade-cro",
			"pricing-strategy",
			"referral-program",
			"free-tool-strategy",
			"paid-ads",
			"crosspost",
			"x-api",
			"image-generation",
			"infographics",
			"omnigen-vault",
			"canvas-design",
		],
		defaultMcp: ["fetch", "firecrawl", "memory"],
		defaultHooks: ["protect-secrets", "session-context"],
	},
	{
		id: "design-ux",
		label: "Design & UX",
		keywords: [
			/design-?system/i,
			/ux-/i,
			/ui-/i,
			/figma/i,
			/product-?design/i,
			/accessibility/i,
			/a11y/i,
			/animation/i,
			/motion/i,
			/typography/i,
			/color-/i,
			/persona-?walkthrough/i,
		],
		skillPool: [
			"design-system",
			"interface-design",
			"frontend-design",
			"frontend-design-direction",
			"color-system",
			"typography-scale",
			"visual-hierarchy",
			"spacing-system",
			"layout-grid",
			"dark-mode-design",
			"responsive-design",
			"motion-system",
			"motion-foundations",
			"motion-patterns",
			"motion-advanced",
			"motion-ui",
			"animation-principles",
			"interaction-design",
			"accessibility",
			"accessibility-audit",
			"accessibility-test-plan",
			"wcag-audit-patterns",
			"audit-and-fix",
			"contrast-checker",
			"link-purpose",
			"use-of-color",
			"user-persona",
			"empathy-map",
			"journey-map",
			"wireframe-spec",
			"design-token",
			"design-brief",
			"design-principles",
			"design-critique",
			"design-taste-frontend",
			"gpt-taste",
			"minimalist-ui",
			"industrial-brutalist-ui",
			"high-end-visual-design",
			"stitch-design-taste",
			"design-lab",
			"ui-design-brain",
			"ui-ux-pro-max",
			"swiss-design",
			"oklch-skill",
		],
		defaultMcp: ["playwright", "chrome-devtools", "context7"],
		defaultHooks: ["pre-shell-guard", "protect-secrets", "post-format"],
	},
	{
		id: "product-pm",
		label: "Product & PM",
		keywords: [
			/product/i,
			/pm-/i,
			/scrum/i,
			/agile/i,
			/roadmap/i,
			/backlog/i,
			/stakeholder/i,
			/requirement/i,
			/project-?shepherd/i,
			/senior-?project/i,
			/sprint-?priorit/i,
			/change-?management/i,
			/strategy-?duel/i,
			/chief-?of-?staff/i,
			/operations-?manag/i,
			/jira-?workflow/i,
			/program-?manag/i,
			/portfolio/i,
		],
		skillPool: [
			"product-lens",
			"product-capability",
			"product-marketing-context",
			"omk-plan",
			"plan",
			"plan-orchestrate",
			"plan-ceo-review",
			"plan-eng-review",
			"plan-design-review",
			"plan-devex-review",
			"plan-tune",
			"blueprint",
			"ulw-plan",
			"deep-interview",
			"intent-driven-development",
			"stakeholder-alignment",
			"metrics-definition",
			"project-flow-ops",
			"competitive-platform-analysis",
			"benchmark-methodology",
			"competitive-report-structure",
			"competitive-analysis",
			"north-star-vision",
			"opportunity-framework",
			"service-blueprint",
			"information-architecture",
			"council",
			"office-hours",
			"brainstorming",
		],
		defaultMcp: ["filesystem", "context7", "github"],
		defaultHooks: ["protect-secrets", "session-context", "branch-diff-snapshot"],
	},
	{
		id: "docs-techwriting",
		label: "Docs & Technical Writing",
		keywords: [
			/docs/i,
			/technical-?writ/i,
			/documentation/i,
			/api-?doc/i,
			/readme/i,
			/tutorial/i,
			/guide/i,
			/knowledge/i,
			/book-?co-?author/i,
			/document-?generat/i,
			/executive-?summary/i,
			/meeting-?notes/i,
			/report-?distribution/i,
			/historian/i,
			/evidence-?collect/i,
			/book/i,
		],
		skillPool: [
			"docs-write-concisely",
			"docs-update-docs",
			"documentation-lookup",
			"documentation-template",
			"document-generate",
			"document-release",
			"doc-coauthoring",
			"docx",
			"pdf",
			"pptx",
			"xlsx",
			"react-pdf",
			"article-writing",
			"internal-comms",
			"knowledge-ops",
			"code-tour",
			"codebase-onboarding",
			"ux-writing",
			"presentation-deck",
			"scientific-slides",
			"slides-grab",
			"slides-grab-plan",
			"slides-grab-design",
			"slides-grab-export",
			"pptx-from-layouts",
			"theme-factory",
			"web-artifacts-builder",
			"excalidraw-diagram",
			"diagram",
		],
		defaultMcp: ["filesystem", "context7"],
		defaultHooks: ["protect-secrets", "post-format"],
	},
	{
		id: "customer-support",
		label: "Customer & Support",
		keywords: [
			/customer/i,
			/support/i,
			/success/i,
			/helpdesk/i,
			/zendesk/i,
			/intercom/i,
			/faq/i,
			/onboard/i,
			/retail-?customer/i,
			/hospitality/i,
		],
		skillPool: [
			"customer-billing-ops",
			"onboarding-cro",
			"onboarding-design",
			"knowledge-ops",
			"ux-writing",
			"error-handling",
			"returns-reverse-logistics",
			"stakeholder-alignment",
			"empathy-map",
			"journey-map",
			"survey-design",
			"metrics-definition",
			"docs-write-concisely",
			"internal-comms",
		],
		defaultMcp: ["filesystem", "memory", "fetch"],
		defaultHooks: ["protect-secrets", "session-context"],
	},
	{
		id: "game-xr",
		label: "Game & XR & Media",
		keywords: [
			/game/i,
			/unity/i,
			/unreal/i,
			/godot/i,
			/xr-/i,
			/vr-/i,
			/ar-/i,
			/metaverse/i,
			/threejs/i,
			/three-/i,
			/webgl/i,
			/bevy/i,
			/3d-/i,
			/roblox/i,
			/studio-/i,
			/video-?optim/i,
			/blender/i,
			/level-?design/i,
			/narrative-?design/i,
			/remotion/i,
			/ffmpeg/i,
			/audio/i,
			/sound/i,
			/music/i,
			/particle/i,
			/shader/i,
			/opengl/i,
		],
		skillPool: [
			"threejs-fundamentals",
			"threejs-geometry",
			"threejs-materials",
			"threejs-lighting",
			"threejs-textures",
			"threejs-shaders",
			"threejs-postprocessing",
			"threejs-animation",
			"threejs-interaction",
			"threejs-loaders",
			"animation-principles",
			"motion-patterns",
			"remotion-best-practices",
			"remotion-video-creation",
			"video-editing",
			"videodb",
			"sounds-on-the-web",
			"generating-sounds-with-ai",
			"mastering-animate-presence",
			"morphing-icons",
			"pseudo-elements",
			"to-spring-or-not-to-spring",
			"12-principles-of-animation",
			"blender-motion-state-inspection",
			"perfectpixel-studio",
			"manim-video",
			"ui-demo",
			"react-native-best-practices",
			"swiftui-ui-patterns",
			"liquid-glass-design",
		],
		defaultMcp: ["filesystem", "context7"],
		defaultHooks: ["pre-shell-guard", "protect-secrets"],
	},
	{
		id: "gis-spatial",
		label: "GIS & Spatial",
		keywords: [
			/gis/i,
			/spatial/i,
			/map-/i,
			/geo-/i,
			/carto/i,
			/postgis/i,
			/satellite/i,
			/remote-?sens/i,
			/real-?estate/i,
			/civil-?engineer/i,
			/drone-?reality/i,
			/geoai/i,
			/geograph/i,
			/geoprocess/i,
			/bim-/i,
			/visionos/i,
			/metal-?engineer/i,
		],
		skillPool: [
			"data-visualization",
			"plotly",
			"networkx",
			"sympy",
			"statistical-analysis",
			"scientific-visualization",
			"matplotlib",
			"seaborn",
			"polars",
			"dask",
			"python-patterns",
			"python-testing",
			"diagram",
			"excalidraw-diagram",
			"threejs-geometry",
			"threejs-materials",
			"threejs-fundamentals",
			"image-generation",
			"swiftui-patterns",
			"swiftui-ui-patterns",
			"swift-concurrency-6-2",
			"threejs-shaders",
			"threejs-interaction",
			"delivery-tracking",
			"gws-tasks",
		],
		defaultMcp: ["filesystem", "context7"],
		defaultHooks: ["pre-shell-guard", "protect-secrets", "post-format"],
	},
	{
		id: "china-regional",
		label: "China & Regional Platforms",
		keywords: [
			/china/i,
			/chinese/i,
			/xiaohongshu/i,
			/weibo/i,
			/wechat/i,
			/douyin/i,
			/bilibili/i,
			/korean/i,
			/japan/i,
			/asia/i,
			/regional/i,
			/localiz/i,
			/i18n/i,
			/translat/i,
			/french-?consult/i,
			/government-/i,
			/cross-?border/i,
			/feishu/i,
			/bilibili/i,
			/zhihu/i,
			/kuaishou/i,
			/livestream/i,
			/short-?video/i,
		],
		skillPool: [
			"agent-reach",
			"insane-search",
			"ultimate-browsing",
			"scrapling",
			"localization-design",
			"brand-voice",
			"copy-editing",
			"market-research",
			"competitive-analysis",
			"pricing-strategy",
			"content-strategy",
			"copywriting",
			"social-content",
			"motion-patterns",
			"animation-principles",
			"remotion-video-creation",
			"image-generation",
			"brandkit",
			"color-system",
			"omnigen-vault",
			"korean-slang-writing",
			"korean-spell-check",
			"korean-character-count",
			"kakaotalk-mac",
			"paid-ads",
			"ab-test-setup",
			"analytics-tracking",
			"customs-trade-compliance",
			"inventory-demand-planning",
			"logistics-exception-management",
			"returns-reverse-logistics",
		],
		defaultMcp: ["fetch", "firecrawl", "memory"],
		defaultHooks: ["protect-secrets", "session-context"],
	},
	{
		id: "hr-people",
		label: "HR & People",
		keywords: [
			/hr-/i,
			/recruit/i,
			/hiring/i,
			/people/i,
			/talent/i,
			/training/i,
			/learn/i,
			/curriculum/i,
			/coach/i,
			/mentor/i,
			/organi[sz]ational/i,
			/anthropolog/i,
			/psycholog/i,
			/cultural-?intelligence/i,
		],
		skillPool: [
			"survey-design",
			"interview-script",
			"user-persona",
			"empathy-map",
			"journey-map",
			"metrics-definition",
			"stakeholder-alignment",
			"knowledge-ops",
			"internal-comms",
			"onboarding-design",
			"docs-write-concisely",
			"gws-people",
			"lead-intelligence",
			"brand-voice",
			"docx",
			"pdf",
			"pptx",
			"xlsx",
			"gws-tasks",
			"gws-calendar",
			"gws-gmail",
		],
		defaultMcp: ["filesystem", "memory"],
		defaultHooks: ["protect-secrets", "session-context"],
	},
];
